# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: /api
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - attach_workspace:
          at: /api
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: go test -v main_test.go
      - run:
          name: Run tests
          command: go build
      - store_test_results:
          path: /tmp/test-reports
    
  
