# Start from golang base image
FROM golang:1.16-alpine

WORKDIR /usr/src/app/server

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /main

EXPOSE 8090

CMD [ "/main" ]
