# Start from golang base image
FROM golang:1.16-alpine

ADD . /usr/src/app/server
WORKDIR /usr/src/app/server

# --no-cache
RUN apk add --update gcc libc-dev

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

#test
#RUN go test -v main_test.go
RUN go build -o /main

EXPOSE 8090
CMD [ "/main" ]
